version: "3.7"

services:
  postgres:
    image: debezium/postgres:13-alpine
    ports:
      - "5432:5432"
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hotel-booking

  app:
    image: hotel-booking
    restart: always
    ports:
      - "8080:8080"
    links:
      - postgres

