micronaut:
  application:
    name: hotelBooking
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3

tracing:
  zipkin:
    enabled: true

jackson:
  date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

flyway:
  enabled: true
  datasources:
    default:
      enabled: true
      driverClassName: org.postgresql.Driver
      dialect: POSTGRES
      url: jdbc:postgresql://postgres:5432/hotel-booking
      username: root
      password: root
datasources:
  default:
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    url: jdbc:postgresql://postgres:5432/hotel-booking
    username: root
    password: root
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://postgres:5432/hotel-booking
      username: root
      password: root
