# global settings
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).


# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'micronaut scrape'
    metrics_path: '/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']